---
# User and group management
- name: install | Ensure group for this play app exists
  group:
    name: "{{ fitnesse_group }}"
    state: present

- name: install | Ensure user for this play app exists
  user:
    name: "{{ fitnesse_username }}"
    groups: "{{ fitnesse_group }}"
    createhome: no
    shell: /bin/bash
    system: yes
    state: present

# File system structure
- name: install | Ensure install directory exists
  file:
    path: "{{ fitnesse_path }}"
    state: directory
    recurse: yes
    owner: "{{ fitnesse_username }}"
    group: "{{ fitnesse_group }}"

- name: install | Ensure install directory exists
  file:
    path: "/var/log/fitnesse"
    state: directory
    recurse: yes
    owner: "{{ fitnesse_username }}"
  become: yes

# Application installation
- name: install | Download application universal package
  get_url:
    url: "{{ fitnesse_url }}"
    dest: "{{ fitnesse_path }}/fitnesse-standalone.jar"
    force: yes
    group: "{{ fitnesse_group }}"
    owner: "{{ fitnesse_username }}"
  notify:
    - restart fitnesse

# Service installation
- name: install | Ensure the upstart configuration exists
  template:
    dest: /etc/init/fitnesse.conf
    src: upstart.j2
    mode: 0644
    owner: root
    group: root
  when: ansible_os_family == 'Debian'
  notify:
    - restart fitnesse
  tags:
    - fitnesse
    - configuration

- name: install | ensure systemd configuration exists
  template:
    dest: /usr/lib/systemd/system/fitnesse.service
    src: systemd.j2
  notify:
   - restart fitnesse
  when: ansible_os_family == 'RedHat'

- name: install | ensure fitnesse service is enable
  systemd:
    daemon_reload: yes
    enabled: yes
    name: fitnesse
  when: ansible_os_family == 'RedHat'
